dist: focal
language: ruby

cache:
  bundler: true
  directories:
    - $HOME/.rvm/

rvm:
  - 3.1.1

branches:
  only:
  - main
  - /^release-.*$/

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'CREATE DATABASE myapp_test;'
  - RAILS_ENV=test bin/rails db:environment:set
  - RAILS_ENV=test bundle exec rake db:create db:migrate

services:
  - mysql

before_install:
  - gem install bundler -v 2.3.7
