arch:
  - amd64
language: ruby
rvm:
  - 3.1.1 # Specify the Ruby version you are using

services:
  - mysql # If your app uses PostgreSQL, otherwise, specify the appropriate database service

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle install
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate

